export const cards = [
    {
      id: 1,
      title: "AI Artists",
      desc: "Add talent to AI",
      img: "https://images.pexels.com/photos/7532110/pexels-photo-7532110.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    },
    {
      id: 2,
      title: "Logo Design",
      desc: "Build yor brand",
      img: "https://images.pexels.com/photos/11295165/pexels-photo-11295165.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    },
    {
      id: 3,
      title: "WordPress",
      desc: "Customize your site",
      img: "https://images.pexels.com/photos/4371669/pexels-photo-4371669.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    },
    {
      id: 4,
      title: "Voice Over",
      desc: "Share your message",
      img: "https://images.pexels.com/photos/7608079/pexels-photo-7608079.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    },
    {
      id: 5,
      title: "Video Explainer",
      desc: "Engage your audience",
      img: "https://images.pexels.com/photos/13388047/pexels-photo-13388047.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    },
    {
      id: 6,
      title: "Social Media",
      desc: "Reach more customers",
      img: "https://images.pexels.com/photos/11378899/pexels-photo-11378899.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    },
    {
      id: 7,
      title: "SEO",
      desc: "Unlock growth online",
      img: "https://images.pexels.com/photos/4820241/pexels-photo-4820241.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    },
    {
      id: 8,
      title: "Illustration",
      desc: "Color you dreams",
      img: "https://images.pexels.com/photos/15032623/pexels-photo-15032623.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    },
  ];
  
  export const projects = [
    {
      id: 1,
      img: "https://images.pexels.com/photos/1462935/pexels-photo-1462935.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Web and Mobile Design",
      username: "Shadan Shilmani",
    },
    {
      id: 2,
      img: "https://images.pexels.com/photos/270408/pexels-photo-270408.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Logo Design",
      username: "Hashem Khosa",
    },
    {
      id: 3,
      img: "https://images.pexels.com/photos/4144923/pexels-photo-4144923.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Animated GIFs",
      username: "Khuram adnan",
    },
    {
      id: 4,
      img: "https://images.pexels.com/photos/4348404/pexels-photo-4348404.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Packaging Design",
      username: "Ibrahim Saad",
    },
    {
      id: 5,
      img: "https://images.pexels.com/photos/4458554/pexels-photo-4458554.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Social Media Design",
      username: "Usman Imtiaz",
    },
    {
      id: 6,
      img: "https://images.pexels.com/photos/4465831/pexels-photo-4465831.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Illustration",
      username: "Amir Mangi",
    },
    {
      id: 7,
      img: "https://images.pexels.com/photos/6077368/pexels-photo-6077368.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Book Design",
      username: "Jannat Junaid",
    },
    {
      id: 8,
      img: "https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1680175/pexels-photo-1680175.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Digital Marketing",
      username: "Faheem umar",
    },
  ];
  
  export const gigs = [
    {
      id: 1,
      img: "https://images.pexels.com/photos/580151/pexels-photo-580151.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create ai art character from your images and prompts",
      price: 3000,
      star: 5,
      username: "Shadan Shilmani",
      category: "AI Artists"
    },
    {
      id: 2,
      img: "https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create ultra high quality character art with ai",
      price: 2200,
      star: 5,
      username: "Samir Idris",
      category: "Illustration"
    },
    {
      id: 3,
      img: "https://images.pexels.com/photos/8797307/pexels-photo-8797307.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will creating unique ai generated artworks mid journey ai artist",
      price: 2000,
      star: 5,
      username: "Fariha Haroon",
      category: "AI Artists"
    },
    {
      id: 4,
      img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create custom ai generated artwork using your photos",
      price: 1500,
      star: 4,
      username: "Rubab Zehra",
      category: "Video Explainer"
    },
    {
      id: 5,
      img: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will recreate your dreams in high quality pictures",
      price: 2000,
      star: 5,
      username: "Arham Adnan",
      category: "Social Media"
    },
    {
      id: 6,
      img: "https://images.pexels.com/photos/8100784/pexels-photo-8100784.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create ai digital art illustration hyper realistic painting",
      price: 1800,
      star: 4,
      username: "Mustafa Ahmed",
      category: "Logo Design"
    },
    {
      id: 7,
      img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will generate images with your prompts using ai dalle",
      price: 2400,
      star: 5,
      username: "Hassan Raheem",
      category: "WordPress"
    },
    {
      id: 8,
      img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create custom art using midjourney generator",
      price: 1500,
      star: 4,
      username: "Ghafoor Ahmed",
      category: "SEO"
    },
    {
      id: 9,
      img: "https://images.pexels.com/photos/755170/pexels-photo-755170.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will design a professional logo for your business",
      price: "1800",
      star: 5,
      username: "Ayesha Khan",
      category: "Logo Design"
    },
    {
      id: 10,
      img: "https://images.pexels.com/photos/1146154/pexels-photo-1146154.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/295176/pexels-photo-295176.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create an engaging video explainer for your product",
      price: "3500",
      star: 4,
      username: "Bilal Ahmad",
      category: "Video Explainer"
    },
    {
      id: 11,
      img: "https://images.pexels.com/photos/776633/pexels-photo-776633.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create high-quality illustrations for books and web",
      price: "2200",
      star: 5,
      username: "Sana Mehmood",
      category: "Illustration"
    },
    {
      id: 12,
      img: "https://images.pexels.com/photos/879707/pexels-photo-879707.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/712229/pexels-photo-712229.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will provide SEO optimization services for your website",
      price: "2500",
      star: 4,
      username: "Faisal Raza",
      category: "SEO"
    },
    {
      id: 13,
      img: "https://images.pexels.com/photos/889899/pexels-photo-889899.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/2150/blur-coffee-cup-drink.jpg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create a voice-over for your advertisement",
      price: "1200",
      star: 5,
      username: "Hira Latif",
      category: "Voice Over"
    },
    {
      id: 14,
      img: "https://images.pexels.com/photos/20786/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/44289/pexels-photo-44289.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will develop a custom WordPress website for your needs",
      price: "5000",
      star: 5,
      username: "Ali Hassan",
      category: "WordPress"
    },
    {
      id: 15,
      img: "https://images.pexels.com/photos/97077/pexels-photo-97077.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/212315/pexels-photo-212315.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create AI-generated art from your concepts",
      price: "3000",
      star: 5,
      username: "Mona Sheikh",
      category: "AI Artists"
    },
    {
      id: 16,
      img: "https://images.pexels.com/photos/144439/pexels-photo-144439.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will design eye-catching social media graphics",
      price: "1500",
      star: 4,
      username: "Nadia Parveen",
      category: "Social Media"
    },
    {
      id: 17,
      img: "https://images.pexels.com/photos/208118/pexels-photo-208118.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/220568/pexels-photo-220568.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create a unique AI-generated avatar for you",
      price: "2000",
      star: 5,
      username: "Qasim Ali",
      category: "AI Artists"
    },
    {
      id: 18,
      img: "https://images.pexels.com/photos/248921/pexels-photo-248921.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/214643/pexels-photo-214643.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will provide a professional voice-over for your podcast",
      price: "1700",
      star: 4,
      username: "Sadia Malik",
      category: "Voice Over"
    },
    {
      id: 19,
      img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will design an effective logo for your startup",
      price: "1900",
      star: 5,
      username: "Junaid Iqbal",
      category: "Logo Design"
    },
    {
      id: 20,
      img: "https://images.pexels.com/photos/20788/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/44291/pexels-photo-44291.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create a dynamic video explainer for your brand",
      price: "3400",
      star: 4,
      username: "Raza Haider",
      category: "Video Explainer"
    },
    {
      id: 21,
      img: "https://images.pexels.com/photos/1006294/pexels-photo-1006294.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1006295/pexels-photo-1006295.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will illustrate your ideas with artistic precision",
      price: "2300",
      star: 5,
      username: "Tariq Nawaz",
      category: "Illustration"
    },
    {
      id: 22,
      img: "https://images.pexels.com/photos/1766693/pexels-photo-1766693.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1766695/pexels-photo-1766695.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will provide top-notch SEO services for your site",
      price: "2700",
      star: 5,
      username: "Zainab Rafiq",
      category: "SEO"
    },
    {
      id: 23,
      img: "https://images.pexels.com/photos/764880/pexels-photo-764880.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/731217/pexels-photo-731217.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create a voice-over for your video in multiple languages",
      price: "1800",
      star: 4,
      username: "Muzammil Khan",
      category: "Voice Over"
    }
    /*
    export const gig = [
      {
          id: 1,
          img: "https://images.pexels.com/photos/580151/pexels-photo-580151.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
          desc: "<p>Exceptional artwork that surpassed my expectations! The artist's creativity and attention to detail are unparalleled. Highly recommended for anyone seeking unique and professional art.</p>",
          price: 3000,
          star: 5,
          username: "Shadan Shilmani",
          category: "AI Artists",
          days_of_delivery: 3,
          country: "Pakistan",
          reviews: 150,
          languages: ["English", "Urdu"],
          skills: ["AI Art", "Character Design"],
          tags: ["AI", "Art", "Character"],
          gig_link: "https://example.com/gig/1"
      },
      {
          id: 2,
          img: "https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
          desc: "<p>The illustrations brought my characters to life in a way I could never have imagined! The artist's talent and dedication to capturing the essence of my story are truly remarkable.</p>",
          price: 2200,
          star: 5,
          username: "Samir Idris",
          category: "Illustration",
          days_of_delivery: 5,
          country: "India",
          reviews: 120,
          languages: ["English", "Hindi"],
          skills: ["Illustration", "AI Art"],
          tags: ["Character Art", "AI", "Illustration"],
          gig_link: "https://example.com/gig/2"
      },
      {
          id: 3,
          img: "https://images.pexels.com/photos/8797307/pexels-photo-8797307.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
          desc: "<p>A fantastic experience! The artist turned my ideas into breathtaking AI-generated artwork. The quality and creativity are top-notch. Will definitely return for more projects.</p>",
          price: 2000,
          star: 5,
          username: "Fariha Haroon",
          category: "AI Artists",
          days_of_delivery: 4,
          country: "Bangladesh",
          reviews: 98,
          languages: ["English", "Bengali"],
          skills: ["AI Art", "Digital Art"],
          tags: ["AI", "Artworks", "MidJourney"],
          gig_link: "https://example.com/gig/3"
      },
      {
          id: 4,
          img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
          desc: "<p>The custom artwork created from my photos was beyond stunning! The artist’s skill and passion shine through in every piece. An absolute joy to work with!</p>",
          price: 1500,
          star: 4,
          username: "Rubab Zehra",
          category: "Video Explainer",
          days_of_delivery: 7,
          country: "Pakistan",
          reviews: 45,
          languages: ["English", "Urdu"],
          skills: ["Digital Art", "Video Creation"],
          tags: ["AI", "Custom Art", "Photos"],
          gig_link: "https://example.com/gig/4"
      },
      {
          id: 5,
          img: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
          desc: "<p>Transforming dreams into visual masterpieces! The artist captured my imagination perfectly, delivering high-quality pictures that exceeded my expectations. Highly talented and professional.</p>",
          price: 2000,
          star: 5,
          username: "Arham Adnan",
          category: "Social Media",
          days_of_delivery: 2,
          country: "India",
          reviews: 67,
          languages: ["English", "Hindi"],
          skills: ["Digital Art", "Photo Editing"],
          tags: ["Dreams", "High Quality", "Pictures"],
          gig_link: "https://example.com/gig/5"
      },
      {
          id: 6,
          img: "https://images.pexels.com/photos/8100784/pexels-photo-8100784.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
          desc: "<p>The hyper-realistic paintings were absolutely phenomenal! The artist's attention to detail and skill in digital art is unmatched. Highly recommend for anyone seeking top-tier illustrations.</p>",
          price: 1800,
          star: 4,
          username: "Mustafa Ahmed",
          category: "Logo Design",
          days_of_delivery: 6,
          country: "Pakistan",
          reviews: 80,
          languages: ["English", "Urdu"],
          skills: ["Digital Art", "Illustration"],
          tags: ["AI", "Hyper Realistic", "Painting"],
          gig_link: "https://example.com/gig/6"
      },
      {
          id: 7,
          img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
          desc: "<p>Incredible service! The images generated with my prompts were unique and creative, far exceeding my expectations. The artist’s expertise with AI tools is impressive. Highly recommend.</p>",
          price: 2400,
          star: 5,
          username: "Hassan Raheem",
          category: "WordPress",
          days_of_delivery: 3,
          country: "Bangladesh",
          reviews: 54,
          languages: ["English", "Bengali"],
          skills: ["AI Art", "Image Generation"],
          tags: ["AI", "DALL·E", "Prompts"],
          gig_link: "https://example.com/gig/7"
      },
      {
          id: 8,
          img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
          desc: "<p>Outstanding custom art created using AI! The artist brought my vision to life with incredible accuracy and creativity. A pleasure to work with and highly professional throughout.</p>",
          price: 1500,
          star: 4,
          username: "Ghafoor Ahmed",
          category: "SEO",
          days_of_delivery: 5,
          country: "Pakistan",
          reviews: 32,
          languages: ["English", "Urdu"],
          skills: ["Custom Art", "AI Generation"],
          tags: ["AI", "Custom Art", "MidJourney"],
          gig_link: "https://example.com/gig/8"
      },
      {
          id: 9,
          img: "https://images.pexels.com/photos/755170/pexels-photo-755170.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1600",
          desc: "<p>Professional logo design that stands out! The designer’s creativity and attention to detail were exactly what I needed for my business. Highly recommend for anyone needing a professional touch.</p>",
          price: 1800,
          star: 5,
          username: "Ayesha Khan",
          category: "Logo Design",
          days_of_delivery: 7,
          country: "India",
          reviews: 110,
          languages: ["English", "Hindi"],
          skills: ["Logo Design", "Branding"],
          tags: ["Logo", "Business", "Professional"],
          gig_link: "https://example.com/gig/9"
      },
      {
          id: 10,
          img: "https://images.pexels.com/photos/1146154/pexels-photo-1146154.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/295176/pexels-photo-295176.jpeg?auto=compress&cs=tinysrgb&w=1600",
          desc: "<p>The explainer video created was engaging and informative! The designer’s ability to simplify complex information into captivating visuals is exceptional. A must-have for any product.</p>",
          price: 3500,
          star: 4,
          username: "Bilal Ahmad",
          category: "Video Explainer",
          days_of_delivery: 10,
          country: "Pakistan",
          reviews: 45,
          languages: ["English", "Urdu"],
          skills: ["Video Creation", "Explainer Video"],
          tags: ["Video", "Engaging", "Product"],
          gig_link: "https://example.com/gig/10"
      },
      {
          id: 11,
          img: "https://images.pexels.com/photos/776633/pexels-photo-776633.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
          desc: "<p>The illustrations for my book were nothing short of amazing! The artist's creativity and attention to detail brought my story to life. Perfect for any author needing high-quality illustrations.</p>",
          price: 2200,
          star: 5,
          username: "Sana Mehmood",
          category: "Illustration",
          days_of_delivery: 6,
          country: "Bangladesh",
          reviews: 50,
          languages: ["English", "Bengali"],
          skills: ["Illustration", "Graphic Design"],
          tags: ["Illustrations", "Books", "Web"],
          gig_link: "https://example.com/gig/11"
      },
      {
          id: 12,
          img: "https://images.pexels.com/photos/879707/pexels-photo-879707.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/712229/pexels-photo-712229.jpeg?auto=compress&cs=tinysrgb&w=1600",
          desc: "<p>Top-notch SEO services that made a significant difference for my website. The expert's knowledge and effective strategies were evident in the results. Highly recommended for any online business.</p>",
          price: 2500,
          star: 4,
          username: "Faisal Raza",
          category: "SEO",
          days_of_delivery: 8,
          country: "Pakistan",
          reviews: 39,
          languages: ["English", "Urdu"],
          skills: ["SEO", "Website Optimization"],
          tags: ["SEO", "Optimization", "Website"],
          gig_link: "https://example.com/gig/12"
      },
      {
          id: 13,
          img: "https://images.pexels.com/photos/889899/pexels-photo-889899.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/2150/blur-coffee-cup-drink.jpg?auto=compress&cs=tinysrgb&w=1600",
          desc: "<p>The voice-over provided was perfect for my advertisement! The artist’s professionalism and the quality of work were beyond my expectations. Ideal for anyone in need of high-quality voice work.</p>",
          price: 1200,
          star: 5,
          username: "Hira Latif",
          category: "Voice Over",
          days_of_delivery: 4,
          country: "India",
          reviews: 75,
          languages: ["English", "Hindi"],
          skills: ["Voice Over", "Audio Production"],
          tags: ["Voice Over", "Advertisement", "Audio"],
          gig_link: "https://example.com/gig/13"
      },
      {
          id: 14,
          img: "https://images.pexels.com/photos/20786/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/44289/pexels-photo-44289.jpeg?auto=compress&cs=tinysrgb&w=1600",
          desc: "<p>Outstanding service! The WordPress website development was smooth and professional. The developer’s expertise and attention to detail resulted in a fantastic website. Highly recommended!</p>",
          price: 5000,
          star: 5,
          username: "Ali Hassan",
          category: "WordPress",
          days_of_delivery: 14,
          country: "Pakistan",
          reviews: 60,
          languages: ["English", "Urdu"],
          skills: ["WordPress Development", "Web Design"],
          tags: ["WordPress", "Website", "Development"],
          gig_link: "https://example.com/gig/14"
      },
      {
          id: 15,
          img: "https://images.pexels.com/photos/97077/pexels-photo-97077.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/212315/pexels-photo-212315.jpeg?auto=compress&cs=tinysrgb&w=1600",
          desc: "<p>The AI-generated art was absolutely stunning! The artist took my concepts and transformed them into extraordinary pieces of art. Highly recommend for anyone looking for unique and creative designs.</p>",
          price: 3000,
          star: 5,
          username: "Mona Sheikh",
          category: "AI Artists",
          days_of_delivery: 3,
          country: "Bangladesh",
          reviews: 88,
          languages: ["English", "Bengali"],
          skills: ["AI Art", "Concept Design"],
          tags: ["AI", "Art", "Concepts"],
          gig_link: "https://example.com/gig/15"
      },
      {
          id: 16,
          img: "https://images.pexels.com/photos/144439/pexels-photo-144439.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
          desc: "<p>Fantastic social media graphics that really stand out! The designer's creativity and quick turnaround made a huge difference for my campaign. Highly recommend for any social media needs.</p>",
          price: 1500,
          star: 4,
          username: "Nadia Parveen",
          category: "Social Media",
          days_of_delivery: 5,
          country: "Pakistan",
          reviews: 40,
          languages: ["English", "Urdu"],
          skills: ["Graphic Design", "Social Media"],
          tags: ["Social Media", "Graphics", "Design"],
          gig_link: "https://example.com/gig/16"
      },
      {
          id: 17,
          img: "https://images.pexels.com/photos/208118/pexels-photo-208118.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/220568/pexels-photo-220568.jpeg?auto=compress&cs=tinysrgb&w=1600",
          desc: "<p>The AI-generated avatar was incredible! The artist captured my ideas perfectly, delivering a unique and eye-catching design. Great experience from start to finish. Highly recommended!</p>",
          price: 2000,
          star: 5,
          username: "Qasim Ali",
          category: "AI Artists",
          days_of_delivery: 4,
          country: "India",
          reviews: 30,
          languages: ["English", "Hindi"],
          skills: ["AI Art", "Avatar Design"],
          tags: ["AI", "Avatar", "Unique"],
          gig_link: "https://example.com/gig/17"
      },
      {
          id: 18,
          img: "https://images.pexels.com/photos/248921/pexels-photo-248921.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/214643/pexels-photo-214643.jpeg?auto=compress&cs=tinysrgb&w=1600",
          desc: "<p>Exceptional voice-over for my podcast! The quality of the recording and the professionalism of the artist exceeded all expectations. Perfect for anyone looking for top-quality voice work.</p>",
          price: 1700,
          star: 4,
          username: "Sadia Malik",
          category: "Voice Over",
          days_of_delivery: 5,
          country: "Pakistan",
          reviews: 20,
          languages: ["English", "Urdu"],
          skills: ["Voice Over", "Podcast Production"],
          tags: ["Voice Over", "Podcast", "Professional"],
          gig_link: "https://example.com/gig/18"
      },
      {
          id: 19,
          img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/209408/pexels-photo-209408.jpeg?auto=compress&cs=tinysrgb&w=1600",
          desc: "<p>Beautiful illustrations for my website! The artist's work was both creative and professional, resulting in stunning visuals that enhanced my online presence. Highly recommend for any web-related art needs.</p>",
          price: 2300,
          star: 5,
          username: "Imran Khan",
          category: "Illustration",
          days_of_delivery: 6,
          country: "India",
          reviews: 55,
          languages: ["English", "Hindi"],
          skills: ["Illustration", "Web Design"],
          tags: ["Illustration", "Website", "Design"],
          gig_link: "https://example.com/gig/19"
      },
      {
          id: 20,
          img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
          pp: "https://images.pexels.com/photos/1261426/pexels-photo-1261426.jpeg?auto=compress&cs=tinysrgb&w=1600",
          desc: "<p>High-quality SEO services that really improved my website's performance. The expert was knowledgeable and delivered excellent results. Great choice for anyone looking to boost their online presence.</p>",
          price: 2800,
          star: 4,
          username: "Ahmed Ali",
          category: "SEO",
          days_of_delivery: 7,
          country: "Bangladesh",
          reviews: 35,
          languages: ["English", "Bengali"],
          skills: ["SEO", "Digital Marketing"],
          tags: ["SEO", "Performance", "Website"],
          gig_link: "https://example.com/gig/20"
      }
  ]
  */
  ];
 